from ..extensions.sqlalchemy import db
from sqlalchemy import Column, Integer, String, Float


class Planet(db.Model):
    # Determines the table name when generated by SQLAlchemy
    __tablename__ = "planets"
    planet_id = Column(Integer, primary_key=True)
    planet_name = Column(String(255))
    planet_type = Column(String(255))
    home_star = Column(String(255))
    mass = Column(Float)
    radius = Column(Float)
    distance = Column(Float)
