from ..extensions.sqlalchemy import db
from sqlalchemy import Column, Integer, String


class User(db.Model):
    # Determines the table name when generated by SQLAlchemy
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    first_name = Column(String(255))
    last_name = Column(String(255))
    email = Column(String(255), unique=True)
    password = Column(String(255))
